# Qn 1

In [2]:
import numpy as np

In [3]:
arr1=np.arange(1,11)

In [4]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Qn 2

In [6]:
arr2=np.zeros((2,3))

In [7]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

# Qn 3

In [8]:
arr3=np.arange(2,21,2)

In [9]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Qn 4

In [11]:
arr1=np.array([1,2,3])

In [12]:
arr2=np.array([4,5,6])

In [13]:
arr1+arr2

array([5, 7, 9])

In [14]:
arr1-arr2

array([-3, -3, -3])

In [15]:
arr1*arr2

array([ 4, 10, 18])

In [16]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

# Qn 5


In [17]:
arr1=np.random.randint(1,101,100)

In [43]:
arr1

array([  1,   2,   2,   2,   2,   3,   5,   5,   6,   8,   8,   9,  11,
        11,  15,  17,  17,  18,  19,  20,  20,  21,  21,  22,  22,  23,
        24,  25,  25,  26,  27,  29,  31,  31,  32,  32,  34,  34,  35,
        36,  37,  37,  39,  41,  42,  43,  44,  44,  45,  47,  49,  49,
        51,  52,  52,  53,  55,  55,  56,  56,  59,  60,  60,  62,  62,
        63,  64,  65,  67,  68,  70,  71,  72,  73,  75,  75,  76,  77,
        77,  78,  79,  80,  81,  81,  86,  87,  89,  90,  92,  92,  93,
        93,  94,  94,  95,  95,  95,  97,  98, 100])

In [44]:
mean=arr1.mean()
mean

48.63

In [45]:
arr1.sort()
arr1

array([  1,   2,   2,   2,   2,   3,   5,   5,   6,   8,   8,   9,  11,
        11,  15,  17,  17,  18,  19,  20,  20,  21,  21,  22,  22,  23,
        24,  25,  25,  26,  27,  29,  31,  31,  32,  32,  34,  34,  35,
        36,  37,  37,  39,  41,  42,  43,  44,  44,  45,  47,  49,  49,
        51,  52,  52,  53,  55,  55,  56,  56,  59,  60,  60,  62,  62,
        63,  64,  65,  67,  68,  70,  71,  72,  73,  75,  75,  76,  77,
        77,  78,  79,  80,  81,  81,  86,  87,  89,  90,  92,  92,  93,
        93,  94,  94,  95,  95,  95,  97,  98, 100])

In [46]:
median=(arr1[49]+arr1[50])/2
median

48.0

In [47]:
std_dev=arr1.std()
std_dev


29.520723229622952

# Qn 6

In [19]:
arr1=np.random.randint(1,101,12)

In [20]:
arr1

array([ 3, 26, 90,  1,  6, 46, 45, 24, 69, 37, 48, 80])

In [21]:
arr1.reshape(3,4)

array([[ 3, 26, 90,  1],
       [ 6, 46, 45, 24],
       [69, 37, 48, 80]])

# Qn 7

In [22]:
arr=np.array([1,2,3,4,5])
np.square(arr)

array([ 1,  4,  9, 16, 25])

# Qn 8

In [23]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Qn 9

In [24]:
A=np.array([1,2,3])
B=np.array([4,5,6])

In [25]:
A.dot(B)

32

# Qn 10

In [26]:
arr1=np.random.randint(1,101,10)

In [27]:
arr1

array([25, 82, 13, 64, 44, 37, 63, 93, 93,  7])

In [28]:
arr1.argmax()

7

In [29]:
arr1.argmin()

9

# Qn 11

In [31]:
a=np.zeros((4,4))
b=np.ones((4,4))
c=np.concatenate((a,b))
d=np.concatenate((a,b),axis=1)
print('vertical concatenation-\n',c)
print('horizontal concatenation-\n',c)

vertical concatenation-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
horizontal concatenation-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Qn 12

In [32]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print('sum of each column is',np.sum(arr,axis=0))
print('sum of each row is',np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of each column is [28 32 36 40]
sum of each row is [10 26 42 58]


# Qn 13

In [35]:
a=np.array([[6,9],[2,8],[1,5]])
b=np.array([[6,4],[5,2],[6,5]])
c=np.intersect1d(a,b)
print("the common elments between a and b are ",c)

the common elments between a and b are  [2 5 6]


# Qn 14

In [36]:
a=np.array([5,-2,3,8,-6,-1])
a[a<0]=0
a

array([5, 0, 3, 8, 0, 0])

# Qn 15

In [37]:
arr1=np.random.randint(1,101,100)
arr1.sort()
arr1

array([  1,   2,   2,   2,   2,   3,   5,   5,   6,   8,   8,   9,  11,
        11,  15,  17,  17,  18,  19,  20,  20,  21,  21,  22,  22,  23,
        24,  25,  25,  26,  27,  29,  31,  31,  32,  32,  34,  34,  35,
        36,  37,  37,  39,  41,  42,  43,  44,  44,  45,  47,  49,  49,
        51,  52,  52,  53,  55,  55,  56,  56,  59,  60,  60,  62,  62,
        63,  64,  65,  67,  68,  70,  71,  72,  73,  75,  75,  76,  77,
        77,  78,  79,  80,  81,  81,  86,  87,  89,  90,  92,  92,  93,
        93,  94,  94,  95,  95,  95,  97,  98, 100])

# Qn 16

In [39]:
a=np.array([9,2,4,6,5])
b=np.array([2,8,15,1,14])
c=np.absolute(a-b)
print("the element wise absolute difference between the two array is ",c)

the element wise absolute difference between the two array is  [ 7  6 11  5  9]


# Qn 17

In [41]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print("first row is\n",firstrow)
print("last column is\n",lastcol)


first row is
 [1 2 3]
last column is
 [[3]
 [6]
 [9]]


# Qn 18

In [42]:
a=np.array([1,2,3,4,5])
x=a[0:len(a)+1]
print(x)

[1 2 3 4 5]


# Qn 19

In [48]:
arr=np.array([[10,1,14,16,18,20],[22,24,26,28,30,32],[34,36,38,40,42,44],[46,48,50,52,54,56],[58,60,62,64,66,68],[70,72,74,76,78,80]])
x=arr[2:4,[2,3]]
print('original array is\n',arr)
print('central 2x2 elements include\n',x)

original array is
 [[10  1 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]
central 2x2 elements include
 [[38 40]
 [50 52]]


# Qn 20

In [49]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])